# Numpy  : Estudio de la libreria y sus funciones

#### Este notebook tiene el proposito general de aprender y colocar en practica el aprendizaje sobre la libreria Numpy para la compresion y su en analisis de datos y estudios en Machine Learnnig

##### ¿Por qué utilizar NumPy?
Las listas de Python son excelentes contenedores de uso general. Pueden serlo “heterogéneos”, lo que significa que pueden contener elementos de diversos tipos, y son bastante rápidos cuando se utilizan para realizar operaciones individuales en un puñado de elementos.

Dependiendo de las características de los datos y de los tipos de operaciones que Si es necesario realizar, otros contenedores pueden ser más apropiados; explotando Con estas características podemos mejorar la velocidad, reducir el consumo de memoria y Ofrecen una sintaxis de alto nivel para realizar una variedad de tareas de procesamiento comunes. NumPy brilla cuando hay grandes cantidades de datos “homogéneos” (del mismo tipo) para ser procesado en la CPU.

#### Setup

In [1]:
import pandas as pd
import numpy as np

#### Crear una Matriz en Numpy

Las matrices NumPy se crean utilizando la función np.array(). Se pueden crear a partir de secuencias de Python, como listas y tuplas.

In [9]:
arr = np.array([1,2,3])
print(arr)
print('\n')
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('\n')
arr = np.array((1,3,2))
print(arr)

[1 2 3]


[[1 2 3]
 [4 5 6]]


[1 3 2]


np.array([1, 2, 3]) crea una matriz unidimensional a partir de una lista.

np.array([[1, 2, 3], [4, 5, 6]]) crea una matriz bidimensional a partir de una lista anidada.

np.array((1, 3, 2)) crea una matriz unidimensional a partir de una tupla.

#### Accediendo al índice de matriz

Se puede acceder a los elementos de una matriz NumPy mediante indexación y segmentación. La indexación recupera elementos específicos, mientras que la segmentación extrae un rango de elementos de una matriz.

In [13]:
arr = np.array([
    [-1,  2, 0,   4],
    [ 4, -0, 5,   6],  
    [ 2,  6, 0,   7], 
    [ 3, -7, 4, 2.0]
])

arr2 = arr[:2 , ::2]
print("Primeras Filas y colummnas alternativas:\n" , arr2)

arr3 = arr[[1,1,0,3],[3,2,1,0]]
print("Elementos seleccionado:",arr3)

Primeras Filas y colummnas alternativas:
 [[-1.  0.]
 [ 4.  5.]]
Elementos seleccionado: [6. 5. 2. 3.]



* arr[:2, ::2] selecciona las dos primeras filas y columnas alternativas (0 y 2).

* arr[[1, 1, 0, 3], [3, 2, 1, 0]] recupera elementos de los pares de índices fila-columna especificados.