# Numpy  : Estudio de la libreria y sus funciones

#### Este notebook tiene el proposito general de aprender y colocar en practica el aprendizaje sobre la libreria Numpy para la compresion y su en analisis de datos y estudios en Machine Learnnig

#### ¿Qué es una matriz?

En programación informática, una matriz es una estructura para almacenar y recuperar datos. A menudo hablamos de una matriz como si fuera una cuadrícula en el espacio, con cada una celda que almacena un elemento de los datos. Por ejemplo, si cada elemento del los datos eran un número, podríamos visualizar una matriz “unidimensional” como una lista

[ 1 , 5 , 2 , 0 ]

Una matriz bidimensional sería como una tabla

Una matriz tridimensional sería como un conjunto de tablas, tal vez apiladas como si estuvieran impresos en páginas separadas. En NumPy, esta idea es generalizado a un número arbitrario de dimensiones, y por tanto el fundamental La clase de matriz se llamandarray: representa un “N-dimensional array”.

 La mayoría de las matrices NumPy tienen algunas restricciones. Por ejemplo:

* Todos los elementos de la matriz deben ser del mismo tipo de datos.

Una vez creada, el tamaño total de la matriz no puede cambiar.

La forma debe ser “rectangular”, no “irregular”; por ejemplo, cada fila de Una matriz bidimensional debe tener el mismo número de columnas.

Cuando se cumplen estas condiciones, NumPy explota estas características para haga que la matriz sea más rápida, más eficiente en memoria y más cómoda de usar que estructuras de datos menos restrictivas.

Para el resto de este documento, utilizaremos la palabra “matriz” para referirnos a una instancia dendarray

##### ¿Por qué utilizar NumPy?
Las listas de Python son excelentes contenedores de uso general. Pueden serlo “heterogéneos”, lo que significa que pueden contener elementos de diversos tipos, y son bastante rápidos cuando se utilizan para realizar operaciones individuales en un puñado de elementos.

Dependiendo de las características de los datos y de los tipos de operaciones que Si es necesario realizar, otros contenedores pueden ser más apropiados; explotando Con estas características podemos mejorar la velocidad, reducir el consumo de memoria y Ofrecen una sintaxis de alto nivel para realizar una variedad de tareas de procesamiento comunes. NumPy brilla cuando hay grandes cantidades de datos “homogéneos” (del mismo tipo) para ser procesado en la CPU.

#### Setup

In [14]:
import pandas as pd
import numpy as np

#### Crear una Matriz en Numpy

Las matrices NumPy se crean utilizando la función np.array(). Se pueden crear a partir de secuencias de Python, como listas y tuplas.

In [9]:
arr = np.array([1,2,3])
print(arr)
print('\n')
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print('\n')
arr = np.array((1,3,2))
print(arr)

[1 2 3]


[[1 2 3]
 [4 5 6]]


[1 3 2]


np.array([1, 2, 3]) crea una matriz unidimensional a partir de una lista.

np.array([[1, 2, 3], [4, 5, 6]]) crea una matriz bidimensional a partir de una lista anidada.

np.array((1, 3, 2)) crea una matriz unidimensional a partir de una tupla.

#### Accediendo al índice de matriz

Se puede acceder a los elementos de una matriz NumPy mediante indexación y segmentación. La indexación recupera elementos específicos, mientras que la segmentación extrae un rango de elementos de una matriz.

In [13]:
arr = np.array([
    [-1,  2, 0,   4],
    [ 4, -0, 5,   6],  
    [ 2,  6, 0,   7], 
    [ 3, -7, 4, 2.0]
])

arr2 = arr[:2 , ::2]
print("Primeras Filas y colummnas alternativas:\n" , arr2)

arr3 = arr[[1,1,0,3],[3,2,1,0]]
print("Elementos seleccionado:",arr3)

Primeras Filas y colummnas alternativas:
 [[-1.  0.]
 [ 4.  5.]]
Elementos seleccionado: [6. 5. 2. 3.]



* arr[:2, ::2] selecciona las dos primeras filas y columnas alternativas (0 y 2).

* arr[[1, 1, 0, 3], [3, 2, 1, 0]] recupera elementos de los pares de índices fila-columna especificados.

#### Operaciones Basicas con Matrices

Las matrices NumPy admiten varias operaciones matemáticas que se pueden realizar en elementos individuales o entre múltiples matrices. Estas operaciones se aplican de manera eficiente sin utilizar bucles explícitos.

In [16]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[4, 3],
              [2, 1]])

print("Adding 1 to every element:\n", a + 1)
print("Subtracting 2 from each element:\n", b - 2)
print("Sum of all array elements:", a.sum())
print("Array sum:\n", a + b)

Adding 1 to every element:
 [[2 3]
 [4 5]]
Subtracting 2 from each element:
 [[ 2  1]
 [ 0 -1]]
Sum of all array elements: 10
Array sum:
 [[5 5]
 [5 5]]


* a + 1 suma 1 a cada elemento de la matriz a.
* b - 2 resta 2 de cada elemento de la matriz b.
* a.sum() devuelve la suma de todos los elementos en a.
* a + b realiza una suma elemento por elemento entre las dos matrices.

#### Tipos de datos en Numpy

Cada matriz NumPy tiene un tipo de datos (dtype) que determina el tipo de valores almacenados en la matriz. NumPy puede detectar automáticamente el tipo de datos o puede especificarlo explícitamente al crear la matriz.

In [19]:
x = np.array([1,2])
print(x.dtype)

x = np.array([1.0,2.0])
print(x.dtype)

x = np.array([1,2] ,dtype = np.int64)
print(x.dtype)

int64
float64
int64


* np.array([1, 2]) crea una matriz de números enteros, por lo que su tipo de datos es int64.
* np.array([1.0, 2.0]) crea una matriz de punto flotante, por lo que su tipo de datos es float64.
* dtype=np.int64 establece explícitamente el tipo de datos de la matriz en int64.
* El atributo dtype se utiliza para ver el tipo de datos de una matriz NumPy.